/**
 *      Copyright 2008 Augusto Campos <b>augcampos&#64augcampos.pt></b><br>
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 3 of the License.
 *      <p>
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *      <p>
 *      You should have received a copy of the GNU General Public License
 *      along with this program; if not, write to the Free Software
 *      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *      MA 02110-1301, USA.
 */
package com.augcampos.gui;

import com.augcampos.core.n501070324_PostoTrabalho;
import com.augcampos.core.n501070324_PostosTrabalho;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 ** @author Augusto Campos <b>augcampos@augcampos.pt</b>
 */
public class n501070324_WorkstationsForm extends javax.swing.JInternalFrame {

    private n501070324_PostosTrabalho postosTrabalhoLnk;

    /** Creates new form n501070324_UserForm
     * @param pt
     */
    public n501070324_WorkstationsForm(n501070324_PostosTrabalho pt) {
        this.postosTrabalhoLnk = pt;
        initComponents();


        tblList.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    editData();
                }
            }
        });

        tblList.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                refreshDetails(getSelect());
            }
        });


        refreshData();
        refreshDetails(getSelect());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tbActions = new javax.swing.JToolBar();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btDelete = new javax.swing.JButton();
        tabsMain = new javax.swing.JTabbedPane();
        pnList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        pnDetails = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCPU = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDisk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRAM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Postos de trabalho");
        setMaximumSize(new java.awt.Dimension(404, 171));
        setMinimumSize(new java.awt.Dimension(404, 171));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tbActions.setFloatable(false);
        tbActions.setRollover(true);
        tbActions.setFocusable(false);
        tbActions.setMinimumSize(new java.awt.Dimension(50, 50));
        tbActions.setPreferredSize(new java.awt.Dimension(25, 25));

        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/augcampos/gui/webdev-add-48x48.png"))); // NOI18N
        btAdd.setText("Adicionar");
        btAdd.setToolTipText("");
        btAdd.setFocusable(false);
        btAdd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        tbActions.add(btAdd);

        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/augcampos/gui/webdev-config-48x48.png"))); // NOI18N
        btEdit.setText("Editar");
        btEdit.setToolTipText("");
        btEdit.setFocusable(false);
        btEdit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        tbActions.add(btEdit);
        tbActions.add(jSeparator1);

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/augcampos/gui/webdev-remove-48x48.png"))); // NOI18N
        btDelete.setText("Apagar");
        btDelete.setToolTipText("");
        btDelete.setFocusable(false);
        btDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        tbActions.add(btDelete);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 100.0;
        getContentPane().add(tbActions, gridBagConstraints);

        pnList.setLayout(new java.awt.GridBagLayout());

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr", "Descricao", "C.P.U.", "Disco", "R.A.M.", "S.O."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.setColumnSelectionAllowed(true);
        tblList.setDoubleBuffered(true);
        tblList.setOpaque(false);
        tblList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblList);
        tblList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblList.getColumnModel().getColumn(0).setPreferredWidth(10);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        pnList.add(jScrollPane1, gridBagConstraints);

        tabsMain.addTab("Listagem", pnList);

        lblNumero.setText("0");

        jLabel1.setText("Numero :");

        jLabel3.setText("C.P.U. ;");

        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/augcampos/gui/webdev-ok-48x48.png"))); // NOI18N
        btSave.setText("Gravar");
        btSave.setMaximumSize(new java.awt.Dimension(100, 50));
        btSave.setMinimumSize(new java.awt.Dimension(100, 50));
        btSave.setPreferredSize(new java.awt.Dimension(150, 50));
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/augcampos/gui/webdev-cancel-48x48.png"))); // NOI18N
        btCancel.setText("Cancelar");
        btCancel.setMaximumSize(new java.awt.Dimension(100, 26));
        btCancel.setMinimumSize(new java.awt.Dimension(100, 26));
        btCancel.setPreferredSize(new java.awt.Dimension(150, 50));
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jLabel4.setText("Disco ;");

        jLabel5.setText("R.A.M. ;");

        jLabel6.setText("S.O. ;");

        jLabel7.setText("Descrição ;");

        javax.swing.GroupLayout pnDetailsLayout = new javax.swing.GroupLayout(pnDetails);
        pnDetails.setLayout(pnDetailsLayout);
        pnDetailsLayout.setHorizontalGroup(
            pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailsLayout.createSequentialGroup()
                .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailsLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnDetailsLayout.createSequentialGroup()
                                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSO, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDisk, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(49, 49, 49)
                                .addComponent(txtCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        pnDetailsLayout.setVerticalGroup(
            pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        tabsMain.addTab("Detalhes", pnDetails);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        getContentPane().add(tabsMain, gridBagConstraints);
        tabsMain.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        addData();
    }//GEN-LAST:event_btAddActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        editData();
    }//GEN-LAST:event_btEditActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        saveData();
}//GEN-LAST:event_btSaveActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        deleteData();
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        cancelData();
    }//GEN-LAST:event_btCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btAdd;
    protected javax.swing.JButton btCancel;
    protected javax.swing.JButton btDelete;
    protected javax.swing.JButton btEdit;
    protected javax.swing.JButton btSave;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel4;
    protected javax.swing.JLabel jLabel5;
    protected javax.swing.JLabel jLabel6;
    protected javax.swing.JLabel jLabel7;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JToolBar.Separator jSeparator1;
    protected javax.swing.JLabel lblNumero;
    protected javax.swing.JPanel pnDetails;
    protected javax.swing.JPanel pnList;
    protected javax.swing.JTabbedPane tabsMain;
    protected javax.swing.JToolBar tbActions;
    protected javax.swing.JTable tblList;
    protected javax.swing.JTextField txtCPU;
    protected javax.swing.JTextField txtDescricao;
    protected javax.swing.JTextField txtDisk;
    protected javax.swing.JTextField txtRAM;
    protected javax.swing.JTextField txtSO;
    // End of variables declaration//GEN-END:variables

    private void refreshData() {
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tblList.getModel();

        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        for (n501070324_PostoTrabalho p : postosTrabalhoLnk.getList()) {
            dtm.addRow(new Object[]{p.getNumero(), p.getDescricao(), p.getCpu(), p.getDisco(), p.getRam(), p.getSo()});
        }
    }

    private void addData() {
        if (tabsMain.getSelectedIndex() == 0) {
            tabsMain.setSelectedIndex(1);
        }

        lblNumero.setText("<Novo>");
        txtDescricao.setText("");
        txtCPU.setText("");
        txtDisk.setText("");
        txtRAM.setText("");
        txtSO.setText("");
        txtDescricao.requestFocus();

    }

    private void editData() {
        if (tabsMain.getSelectedIndex() == 0) {
            tabsMain.setSelectedIndex(1);
        }
        refreshDetails(getSelect());
        txtDescricao.select(0, 9999);
        txtDescricao.requestFocus();

    }

    private void deleteData() {
        postosTrabalhoLnk.remove(getSelect());
        refreshData();
    }

    private void saveData() {

        n501070324_PostoTrabalho posto;
        if (lblNumero.getText().equalsIgnoreCase("<Novo>")) {
            posto = new n501070324_PostoTrabalho();
            postosTrabalhoLnk.add(posto);
        } else {
            posto = getSelect();
        }
        posto.setDescricao(txtDescricao.getText());
        posto.setCpu(txtCPU.getText());
        posto.setDisco(txtDisk.getText());
        posto.setRam(txtRAM.getText());
        posto.setSo(txtSO.getText());
        refreshData();
        refreshDetails(posto);
    }

    private void cancelData() {
        refreshDetails(getSelect());
    }

    private void refreshDetails(n501070324_PostoTrabalho postoTrabalho) {
        if (postoTrabalho != null) {
            lblNumero.setText("" + postoTrabalho.getNumero());
            txtDescricao.setText(postoTrabalho.getDescricao());
            txtCPU.setText(postoTrabalho.getCpu());
            txtDisk.setText(postoTrabalho.getDisco());
            txtRAM.setText(postoTrabalho.getRam());
            txtSO.setText(postoTrabalho.getSo());
        }
    }

    private n501070324_PostoTrabalho getSelect() {
        if (tblList.getRowCount() < 1) {
            return null;
        }
        if (tblList.getSelectedRow() == -1) {
            tblList.setRowSelectionInterval(0, 0);
        }
        int id = Integer.valueOf(tblList.getModel().getValueAt(tblList.getSelectedRow(), 0).toString());


        return postosTrabalhoLnk.getPostoTrabalho(id);
    }
}
